"""Writes Sources/BrochachoCore/DefaultTunings.swift from defaults/tunings.json."""
import json, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
tunings = json.loads((root / 'defaults' / 'tunings.json').read_text())
rows = ['        Tuning(id: %s, instrument: %s, name: %s, strings: [%s])' % (
    json.dumps(t['id']), json.dumps(t['instrument']), json.dumps(t['name']), ', '.join(json.dumps(s) for s in t['strings']))
    for t in tunings]
out = '''// GENERATED by scripts/gen_default_tunings.py from defaults/tunings.json. Do not edit by hand.
import Foundation

public enum DefaultTunings {
    public static let all: [Tuning] = [
%s
    ]
}
''' % ',\n'.join(rows)
(root / 'Sources' / 'BrochachoCore' / 'DefaultTunings.swift').write_text(out)
print('wrote DefaultTunings.swift with', len(rows), 'tunings')
