"""Writes Sources/BrochachoCore/DefaultCatalog.swift from defaults/catalog.json,
so the Swift defaults and the JS reference can never drift apart."""
import json, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
entries = json.loads((root / 'defaults' / 'catalog.json').read_text())

def s(v):
    return 'nil' if v is None else json.dumps(v, ensure_ascii=False)

rows = []
for e in entries:
    aliases = '[' + ', '.join(json.dumps(a) for a in e.get('aliases', [])) + ']'
    rows.append(
        '        CatalogEntry(name: %s, display: %s, aliases: %s, kind: .%s, target: %s, profile: %s, searchTemplate: %s)'
        % (s(e['name']), s(e.get('display')), aliases, e['kind'], s(e['target']), s(e.get('profile')), s(e.get('searchTemplate'))))

out = '''// GENERATED by scripts/gen_default_catalog.py from defaults/catalog.json. Do not edit by hand.
import Foundation

public enum DefaultCatalog {
    public static let entries: [CatalogEntry] = [
%s
    ]
}
''' % ',\n'.join(rows)
(root / 'Sources' / 'BrochachoCore' / 'DefaultCatalog.swift').write_text(out)
print('wrote DefaultCatalog.swift with', len(rows), 'entries')
